aa: rand-n3-m10-mstd0.5-inc1 #rand-m9-mstd0.5-inc1 #m9-n2-mstd0.5-inc1 (random augment) (autoaug x)
amp: true
batch_size: 128
candfile: ./interval_cands/tiny.json
cfg: ./experiments/supernet/tiny.yaml
change_qkv: true
clip_grad: null
color_jitter: 0.4
cooldown_epochs: 10
cutmix: 1.0 #0.0
cutmix_minmax: null
data_path: /data
data_set: IMNET
decay_epochs: 30
decay_rate: 0.1
device: cuda
dist_backend: nccl
dist_eval: true
dist_url: tcp://localhost:2042
distributed: true
drop: 0.0
drop_block: null
drop_path: 0.1
epochs: 500
eval: false
eval_crops: 1
gp: true
gpu: 0
group_by_depth: true
group_by_dim: true
inat_category: name
input_size: 224
lr: 0.0005
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lr_power: 1.0
max_relative_position: 14
min_lr: 1.0e-07
mixup: 0.8 #0.0
mixup_mode: elem #x
mixup_prob: 1.0 #0.0 ???
mixup_switch_prob: 0.5 #0.0
mode: super
model: ''
model_ema: false
model_ema_decay: 0.99996
model_ema_force_cpu: false
momentum: 0.9
no_abs_pos: false
no_sandwich_base: false
no_sandwich_top: false
num_workers: 10
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output_dir: ./output/tiny/train/2024_07_23-19_48_51
patch_size: 16
patience_epochs: 10
pin_mem: true
platform: pai
post_norm: false
print2file: false
rank: 0
recount: 2 # 1
relative_position: true
remode: pixel
repeated_aug: true
reprob: 0.25
resplit: false
resume: output/tiny/train/2024_07_18-12_40_28/checkpoint-460.pth
rpe_type: bias
sandwich: 0
scale_attn: false
scale_embed: false
scale_mlp: false
sched: cosine
seed: 0
shuffle: false
smoothing: 0.1
start_epoch: 0
switch_ln: false
task: ''
teacher_model: ''
train_interpolation: bicubic
warmup_epochs: 20
warmup_lr: 1.0e-06
weight_decay: 0.05 #0.02
world_size: 8
